version: "3.8"

services:
  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - db
    links:
      - db
  db:
    image: mongo:4.0-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - node-test:/data/db

volumes:
  node-test: 
